/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * API version: 2.0
 * Contact: support@bitbucket.org
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket_client

import (
	"encoding/json"
)

// DeploymentState struct for DeploymentState
type DeploymentState struct {
	Object
}

// NewDeploymentState instantiates a new DeploymentState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentState(type_ string) *DeploymentState {
	this := DeploymentState{}
	this.Type = type_
	return &this
}

// NewDeploymentStateWithDefaults instantiates a new DeploymentState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentStateWithDefaults() *DeploymentState {
	this := DeploymentState{}
	return &this
}

func (o DeploymentState) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedObject, errObject := json.Marshal(o.Object)
	if errObject != nil {
		return []byte{}, errObject
	}
	errObject = json.Unmarshal([]byte(serializedObject), &toSerialize)
	if errObject != nil {
		return []byte{}, errObject
	}
	return json.Marshal(toSerialize)
}

type NullableDeploymentState struct {
	value *DeploymentState
	isSet bool
}

func (v NullableDeploymentState) Get() *DeploymentState {
	return v.value
}

func (v *NullableDeploymentState) Set(val *DeploymentState) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentState) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentState(val *DeploymentState) *NullableDeploymentState {
	return &NullableDeploymentState{value: val, isSet: true}
}

func (v NullableDeploymentState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


