/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * API version: 2.0
 * Contact: support@bitbucket.org
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket_client

import (
	"encoding/json"
)

// PipelinesDdevPipelineStep struct for PipelinesDdevPipelineStep
type PipelinesDdevPipelineStep struct {
	Object
}

// NewPipelinesDdevPipelineStep instantiates a new PipelinesDdevPipelineStep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelinesDdevPipelineStep(type_ string) *PipelinesDdevPipelineStep {
	this := PipelinesDdevPipelineStep{}
	this.Type = type_
	return &this
}

// NewPipelinesDdevPipelineStepWithDefaults instantiates a new PipelinesDdevPipelineStep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelinesDdevPipelineStepWithDefaults() *PipelinesDdevPipelineStep {
	this := PipelinesDdevPipelineStep{}
	return &this
}

func (o PipelinesDdevPipelineStep) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedObject, errObject := json.Marshal(o.Object)
	if errObject != nil {
		return []byte{}, errObject
	}
	errObject = json.Unmarshal([]byte(serializedObject), &toSerialize)
	if errObject != nil {
		return []byte{}, errObject
	}
	return json.Marshal(toSerialize)
}

type NullablePipelinesDdevPipelineStep struct {
	value *PipelinesDdevPipelineStep
	isSet bool
}

func (v NullablePipelinesDdevPipelineStep) Get() *PipelinesDdevPipelineStep {
	return v.value
}

func (v *NullablePipelinesDdevPipelineStep) Set(val *PipelinesDdevPipelineStep) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelinesDdevPipelineStep) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelinesDdevPipelineStep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelinesDdevPipelineStep(val *PipelinesDdevPipelineStep) *NullablePipelinesDdevPipelineStep {
	return &NullablePipelinesDdevPipelineStep{value: val, isSet: true}
}

func (v NullablePipelinesDdevPipelineStep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelinesDdevPipelineStep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


