/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * API version: 2.0
 * Contact: support@bitbucket.org
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket_client

import (
	"encoding/json"
)

// PipelineStateCompletedSuccessful struct for PipelineStateCompletedSuccessful
type PipelineStateCompletedSuccessful struct {
	PipelineStateCompletedResult
	// The name of the successful result (SUCCESSFUL).
	Name *string `json:"name,omitempty"`
}

// NewPipelineStateCompletedSuccessful instantiates a new PipelineStateCompletedSuccessful object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineStateCompletedSuccessful(type_ string) *PipelineStateCompletedSuccessful {
	this := PipelineStateCompletedSuccessful{}
	this.Type = type_
	return &this
}

// NewPipelineStateCompletedSuccessfulWithDefaults instantiates a new PipelineStateCompletedSuccessful object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineStateCompletedSuccessfulWithDefaults() *PipelineStateCompletedSuccessful {
	this := PipelineStateCompletedSuccessful{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PipelineStateCompletedSuccessful) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineStateCompletedSuccessful) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PipelineStateCompletedSuccessful) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PipelineStateCompletedSuccessful) SetName(v string) {
	o.Name = &v
}

func (o PipelineStateCompletedSuccessful) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedPipelineStateCompletedResult, errPipelineStateCompletedResult := json.Marshal(o.PipelineStateCompletedResult)
	if errPipelineStateCompletedResult != nil {
		return []byte{}, errPipelineStateCompletedResult
	}
	errPipelineStateCompletedResult = json.Unmarshal([]byte(serializedPipelineStateCompletedResult), &toSerialize)
	if errPipelineStateCompletedResult != nil {
		return []byte{}, errPipelineStateCompletedResult
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullablePipelineStateCompletedSuccessful struct {
	value *PipelineStateCompletedSuccessful
	isSet bool
}

func (v NullablePipelineStateCompletedSuccessful) Get() *PipelineStateCompletedSuccessful {
	return v.value
}

func (v *NullablePipelineStateCompletedSuccessful) Set(val *PipelineStateCompletedSuccessful) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineStateCompletedSuccessful) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineStateCompletedSuccessful) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineStateCompletedSuccessful(val *PipelineStateCompletedSuccessful) *NullablePipelineStateCompletedSuccessful {
	return &NullablePipelineStateCompletedSuccessful{value: val, isSet: true}
}

func (v NullablePipelineStateCompletedSuccessful) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineStateCompletedSuccessful) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


