/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * API version: 2.0
 * Contact: support@bitbucket.org
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket_client

import (
	"encoding/json"
)

// StgWestReport struct for StgWestReport
type StgWestReport struct {
	Object
}

// NewStgWestReport instantiates a new StgWestReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStgWestReport(type_ string) *StgWestReport {
	this := StgWestReport{}
	this.Type = type_
	return &this
}

// NewStgWestReportWithDefaults instantiates a new StgWestReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStgWestReportWithDefaults() *StgWestReport {
	this := StgWestReport{}
	return &this
}

func (o StgWestReport) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedObject, errObject := json.Marshal(o.Object)
	if errObject != nil {
		return []byte{}, errObject
	}
	errObject = json.Unmarshal([]byte(serializedObject), &toSerialize)
	if errObject != nil {
		return []byte{}, errObject
	}
	return json.Marshal(toSerialize)
}

type NullableStgWestReport struct {
	value *StgWestReport
	isSet bool
}

func (v NullableStgWestReport) Get() *StgWestReport {
	return v.value
}

func (v *NullableStgWestReport) Set(val *StgWestReport) {
	v.value = val
	v.isSet = true
}

func (v NullableStgWestReport) IsSet() bool {
	return v.isSet
}

func (v *NullableStgWestReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStgWestReport(val *StgWestReport) *NullableStgWestReport {
	return &NullableStgWestReport{value: val, isSet: true}
}

func (v NullableStgWestReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStgWestReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


